version: '3'
services:
  node_express:
    build: ./
    container_name: ebook
    volumes:
      - "${CONTENST_ROOT}:/app/contents"
      - "${WORKFILE_DIR}:/app/workdir"
    ports:
      - "${PORT}:80"